### ISSUE TITLE
Configure end-point probe-time,retry values etc from kube-loxilb

### ISSUE THREAD

**Issue by TrekkieCoder** [loxilb-io/kube-loxilb#105]
Currently, some values needed to configure end-points like probing timer and retry values need to be manually configured using loxicmd. Otherwise the default values in loxilb are used which may not be suitable for everyone. Linked to this [issue](https://github.com/loxilb-io/loxilb/issues/546)

**Comment by UltraInstinct14** [comment]
The support has been added. More details can be found in the linked [issue](https://github.com/loxilb-io/loxilb/issues/546).
