### ISSUE TITLE
Support for IPAM range 

### ISSUE THREAD

**Issue by UltraInstinct14** [loxilb-io/kube-loxilb#137]
Currently kube-loxilb configuration needs IPAM to be specified as a prefix. For more user-friendly configuration, it would be great if kube-loxilb can support IPAM range as configuration. For example : ```- --externalCIDR=192.168.80.200-192.168.80.205```

**Comment by 6547709** [comment]
I recently encountered this requirement. Since there are not many available IPs left in the subnet, when will it be supported?

**Comment by TrekkieCoder** [comment]
@6547709 This is set to be supported in ~ 2 weeks time frame from now.

**Comment by TrekkieCoder** [comment]
The IPAMs can be specified as range now ```- --externalCIDR=192.168.80.200-192.168.80.205``` in kube-loxilb args or in CRD.
