### ISSUE TITLE
SCTP Load Balancing on Kubernetes

### ISSUE THREAD

**Issue by souravpaul8** [loxilb-io/kube-loxilb#142]
Can loxiLB redirect requests from an existing SCTP connection to a new replica if the original replica goes down? If yes, how does this redirection work? Can loxiLB do this without any change on the client side ? If yes then how ?

**Comment by UltraInstinct14** [comment]
Loxilb in fullproxy mode can perform such failover. Currently this feature is available when using sctp N2  interface.

**Comment by UltraInstinct14** [comment]
We are finally here with [support](https://www.loxilb.io/post/ngap-load-balancing-with-loxilb) for stateful SCTP application. I hope you find it useful.
