### ISSUE TITLE
In-cluster mode with Cilium?

### ISSUE THREAD

**Issue by stevefan1999-personal** [loxilb-io/kube-loxilb#158]
Load balancing doesn't seems to work in my case where I have Cilium installed, nor it was documented, is it supported?

**Comment by UltraInstinct14** [comment]
Due to both cilium and loxilb using their own eBPF implementations, loxilb (in-cluster mode) and cilium might be incompatible. And I believe nobody has given a serious enough try. 

Nonetheless, I will give it a try and report more details.

**Comment by UltraInstinct14** [comment]
Update - It is possible to run loxilb(in-cluster mode) and cilium provided you run loxilb pod with multus. There is [guide](https://docs.loxilb.io/quick_start_with_cilium/) of running loxilb(external mode) with cilium. In this guide, loxilb runs as a docker in the same pod and uses mac-vlan interface to get packets to itself before cilium gets hands on it. 

In the same way, loxilb pod in-cluster can use multus to get a secondary interface hooked to it and get things working. There was a [blog](https://futuredon.medium.com/5g-sctp-loadbalancer-using-loxilb-b525198a9103) which used a similar concept although not with cilium. Will try to write a README for this when time permits.

**Comment by TrekkieCoder** [comment]
Updated guide [here](https://docs.loxilb.io/latest/cilium-incluster)
