### ISSUE TITLE
Service creation failed error handling

### ISSUE THREAD

**Issue by nik-netlox** [loxilb-io/kube-loxilb#16]
It was observed that when a service is created with InactiveTimeout more than Allowed Timeout Value(24*3600) then loxilb returns error but kube-loxilb shows success.

**Comment by TrekkieCoder** [comment]
kube-loxilb used to check http status code, which is usually 200 (OK) . The return code is passed as a "Success" or "Error" string in the body.  Parsing code as expected has been implemented and verified.
