### ISSUE TITLE
Support for in-cluster management of loxilb

### ISSUE THREAD

**Issue by PacketCrunch** [loxilb-io/kube-loxilb#18]
Currently, as a preferred method, loxilb runs outside cluster while kube-loxilb runs inside cluster. But we should be able to manage loxilb inside cluster as well.

**Comment by UltraInstinct14** [comment]
We need to confirm if there are any issues to support in-cluster mode on AWS after this :

https://aws.amazon.com/blogs/containers/amazon-vpc-cni-now-supports-kubernetes-network-policies/
