### ISSUE TITLE
Is it Possible to Support Configuring the “usepodnetwork” Option as a Parameter in kube-loxilb

### ISSUE THREAD

**Issue by 6547709** [loxilb-io/kube-loxilb#198]
Background: I previously used VMware’s NSX ALB (AVI) as a load balancer for Kubernetes, which supports both LoadBalancer and Ingress, and advertises Pod routes to the Controller. This setup allows bypassing kube-proxy, with the load balancing strategy applied only at the load balancer level. The deployment architecture was similar to LoxiLB’s external cluster architecture. Currently, I am using LoxiLB as a replacement, and my architecture is as follows:

1、Two Fedora Core virtual machines are used as external LoxiLB nodes (running Docker).
2.、The external LoxiLB nodes have two network interfaces: one for the VIP and the other for communication with Kubernetes cluster nodes.
3、The Kubernetes cluster is built using Talos Linux with Cilium as the CNI (without kube-proxy).
4、A BGP connection is established between the external LoxiLB and the cluster through the Cilium Agent, and BGP connections are configured between kube-loxilb and Cilium for LoxiLB to learn Pod routes.
5、Kube-loxilb is configured with --externalCIDR set to LoxiLB’s VIP range.
![Loxilb-Pod-Route](https://github.com/user-attachments/assets/74cef995-2873-447f-8dae-ad03fb107f94)

I have successfully implemented direct traffic forwarding from the external LoxiLB to Pods and can flexibly use LoxiLB’s load balancing algorithms. 
LoxiLB is amazing, and I really like it.
However, there are a few areas that are not ideal:

1、The “usepodnetwork” option can only be configured on a per-service basis and cannot be set globally in kube-loxilb.
2、The --setBGP and --extBGPpeers parameters in kube-loxilb can only be used for either external or internal configurations. It becomes difficult to have the external LoxiLB establish BGP connections with both physical routers and Kubernetes cluster nodes simultaneously. Supporting separate sets of BGP parameters for external and internal use would greatly enhance flexibility. Alternatively, enabling kube-loxilb to directly publish Pod routing tables to LoxiLB (while keeping the existing parameters unchanged) would be beneficial.

I am aware of potential architectural issues with advertising Pod routes to LoxiLB, such as routing conflicts when multiple Kubernetes clusters use the same PodCIDR. Currently, I define unique PodCIDRs for each Kubernetes cluster to avoid overlaps. I am curious if there are better solutions for handling identical PodCIDRs, such as using VRF technology.

**Comment by TrekkieCoder** [comment]
Hi @6547709 

Thanks for the detailed scenario and explanation.  Answers to some of your questions :

>1、The “usepodnetwork” option can only be configured on a per-service basis and cannot be set globally in kube-loxilb.

This can and will be taken up as an enhancement.

> 2、The --setBGP and --extBGPpeers parameters in kube-loxilb can only be used for either external or internal configurations. It becomes difficult to have the external LoxiLB establish BGP connections with both physical routers and Kubernetes cluster nodes simultaneously. Supporting separate sets of BGP parameters for external and internal use would greatly enhance flexibility. 

On this end, we have been working on BGP configuration using [CRDs](https://github.com/loxilb-io/loxilbdocs/blob/main/docs/k8s_bgp_policy_crd.md). Although this is in beta, we are trying our best to get it into good shape. Please give it a try. The community will help if you run into any trouble.

>  Alternatively, enabling kube-loxilb to directly publish Pod routing tables to LoxiLB (while keeping the existing parameters unchanged) would be beneficial. 

Need some more pondering on this.

**Comment by 6547709** [comment]
Thanks for your help, these are not real operational issues, but my ideas to make LoxiLB more powerful^_^

I will test CRD configuration BGP routing;

Regarding the announcement of Pod routes, currently, I am going to write a small program to automatically update the Pod routes through the LoxiLB API interface (/config/route).

**Comment by 6547709** [comment]
But I found a problem with the API. The current API does not have any authentication. Anyone can directly operate the LoxiLB API. Did I miss some authentication configuration?

**Comment by TrekkieCoder** [comment]
Yes you are right. In the process of supporting it via [this](https://github.com/loxilb-io/kube-loxilb/issues/34) along with OAuth based authentication scheme.
