### ISSUE TITLE
Question about working mechanism when adding a new worker node

### ISSUE THREAD

**Issue by sykim-etri** [loxilb-io/kube-loxilb#2]
I visited on [your blog](https://ko.loxilb.io/post/eks%EC%97%90%EC%84%9C-loxilb-%EB%A1%9C%EB%93%9C%EB%B0%B8%EB%9F%B0%EC%84%9C-%EC%84%A4%EC%A0%95) about configuration of LoxiLB with EKS.

I have questions about working mechanism of kube-loxilb when adding/removing a new worker node.
As I reviewed the kube-loxilb code briefly, I could not find the code for adding/removing member of LoxiLB when adding/removing a new worker node.

Is is working on that scenario?
If so, could I find the related code? or if not, do you have a plan about it?

Thanks for your contribution.

**Comment by backguynn** [comment]
hello.

kube-loxilb is provided worker nodes list by kubernetes,
and this list symply uses as load balancer endpoints.

If a worker node is newly added/deleted, kubernetes sends an update event to kube-loxilb. Using that information, kube-loxilb updates the load balancer rules.

But I'll check again if the endpoint of the load balancer rule is actually updated.

Thanks for the new comments.

**Comment by sykim-etri** [comment]
@backguynn  Thanks for your comment. And Could you recommend some references to understand the kube-loxilb? kubernetes documents, similar open source project, or so on

**Comment by backguynn** [comment]
Information about kube-loxilb can be found in [this document.](https://loxilb-io.github.io/loxilbdocs/kube-loxilb/) only for now.
This document contains only a brief description, because kube-loxilb has only implemented k8s LoadBalancerClass for loxilb.

For more understanding, I recommend you check the contents of loxilb.
But if you have any other questions about kube-loxilb, feel free to comment.

**Comment by NLX-SeokHwanKong** [comment]
Maybe, first need to check about the k8s load balancer class(https://kubernetes.io/docs/concepts/services-networking/service/#load-balancer-class)

 you can also check source codes in metallb and vip.

https://kube-vip.io/docs/usage/kubernetes-services/

https://github.com/metallb/metallb/pull/1417

**Comment by loxi-admin** [comment]
> hello.
> 
> kube-loxilb is provided worker nodes list by kubernetes, and this list symply uses as load balancer endpoints.
> 
> If a worker node is newly added/deleted, kubernetes sends an update event to kube-loxilb. Using that information, kube-loxilb updates the load balancer rules.
> 
> But I'll check again if the endpoint of the load balancer rule is actually updated.
> 
> Thanks for the new comments.

This has been reported to be not working properly by another user.  We will work on it.

**Comment by TrekkieCoder** [comment]
@sykim-etri  Please refer to [this]( https://github.com/loxilb-io/kube-loxilb/commit/40b1c3e1c01988a79d03f9fc53d6d8b6aacaba60)

**Comment by TrekkieCoder** [comment]
Verified to be working fine in EKS by @backguynn . Closing this !!
