### ISSUE TITLE
Some codes for controlling nodes?

### ISSUE THREAD

**Issue by sykim-etri** [loxilb-io/kube-loxilb#39]
I have a question about an existence of codes for controlling nodes in kube-loxilb.

According to README.md, kube-loxilb seems to be only related to kubernetes service load-balancer spec.
> [kube-loxilb](https://github.com/loxilb-io/kube-loxilb) is loxilb's implementation of kubernetes service load-balancer spec which includes support for load-balancer class, advanced IPAM (shared or exclusive) etc.

If there are some code for controlling nodes, please let me know about it.
Thanks for your attention.

**Comment by backguynn** [comment]
hello.
kube-loxilb retrieves node list information from K8s when a LoadBalancer type service is created.
If a node is added/deleted, a service's update event occurs. At this time, the node list information is retrieved again, 
And the endpoint of the service is modified with the updated node list.
This is all kube-loxilb does for now to control nodes.
(https://github.com/loxilb-io/kube-loxilb/blob/86e18dcedb8ef91e9a14a6f5a9c9905e31763f18/pkg/agent/manager/loadbalancer/loadbalancer.go#L399)

Currently it works fine for when nodes are added, But there seems to be a problem when nodes are deleted.
I will comment again once the error is corrected.

**Comment by backguynn** [comment]
Updated to remove the LB endpoint when a node's state changes to NotReady/Unknown.

https://github.com/loxilb-io/kube-loxilb/pull/41
