### ISSUE TITLE
Load balancer should be deleted when kubernetes service is deleted

### ISSUE THREAD

**Issue by aerosouund** [loxilb-io/kube-loxilb#58]
I created a k8s service with loadbalancer type and it got registered with loxilb as shown in the output of `loxicmd get lb`

```bash
|  EXTERNAL IP   | PORT  | PROTOCOL | MARK | SELECT |  MODE   | # OF ENDPOINTS | MONITOR |
|----------------|-------|----------|------|--------|---------|----------------|---------|
| 192.168.65.103 |  3000 | tcp      |    0 | rr     | fullnat |              7 | Off     |
```

If i delete the service the get lb command still shows it

I'm running loxilb from code as per this guide https://loxilb-io.github.io/loxilbdocs/run/

K8s engine: EKS 1.23
LoxiLB node: external, ubuntu 20.04
Kube-loxilb options:

```bash
      - '--loxiURL=http://192.168.65.103:11111'
      - '--setLBMode=2'
      - '--externalCIDR=192.168.65.103/32'
      - '--setRoles=0.0.0.0'
```

**Comment by aerosouund** [comment]
If this is an actual issue and not a misconfiguration from my side then i'd love to submit a PR that fixes it please

**Comment by TrekkieCoder** [comment]
When the service is deleted the correspinding rule in loxilb should be deleted . However not sure why it is not happening in your specific case. Will be happy to accept PR if you can pinpoint the issue in code.

**Comment by aerosouund** [comment]
Awesome, ill review it and submit a PR if i discover something

**Comment by TrekkieCoder** [comment]
Closing this as this has been validated to be working fine. If you face further issues, kindly reopen !!
